language: ruby
rvm:
 - 2.2.0
 - jruby
 - rbx-2
# before_script:
#  - bundle install
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
