language: ruby
rvm:
 - 2.2.0
 - jruby
 # - rbx-2
before_install:
 - rvm install ruby -v 2.2.0p0
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec cucumber
after_script:
  - bundle exec rake send_to_codeclimate 