# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca7096cbaeeefdd4a0ae0bc08dce6ae02edc1f0afff6714043182ba698933797efa2c5328c1bf15896100210726ca3dce39a96e2d0fae0a1cd330d02e64a405c

test:
  secret_key_base: 9ab4589e52945f7306d50b65346f2272f42ceaa5a79c131b044460a521bd4cbfec611bce74067962d346cb27f114d457e891c3373854fe6aedc5f755054c0914

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
